### ISSUE TITLE
Task list - o que falta escrever

### ISSUE THREAD

**Issue by temospena** [U-Shift/Transport-Demand-Modelling#4]
Assinalar quando estiver pronto e com link para o `.r` ou `.md` no índice do [README](https://github.com/U-Shift/Transport-Demand-Modelling/README.md)
-  [x] 1. Exploratory Data Analysis (@valenca13 )
- [x] 2. Multiple Regression Analysis (@valenca13 )
- [x] 3. Factor Analysis (@valenca13 )
- [x] 4. Cluster Analysis (@valenca13 )
- [x] 5. Generalized linear models (@valenca13 )
- [x] 6. Spatial regression models
- [x] 6.1. Moran's I (@temospena)
- [x] 7.  Panel Data Modelling (@valenca13 )
- [x] 8. Discrete Choice Models (@mncosta , @filmoura )
- [x]        8.1. Multinomial - Nested
- [x]        8.2. Multinomial - Ordered Models
- [x] 9.  Hazard-Based Duration Models (@valenca13 ) Adapt from the script of Carlos Roque

Other
- [x]  How to install R (@temospena )
- [ ]  How to produce markdown reports (.md .pdf .html) (@temospena)
